# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_employmentv1_is_current_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofilev1',
            name='assets_verification_method',
            field=models.CharField(blank=True, choices=[('self_reported', 'Self Reported'), ('yodlee', 'Yodlee Aggregated assets')], max_length=127, null=True),
        ),
    ]
