from website.settings.utils import get_env_variable

ADVISOR_STORAGE_HOOK_ENABLE = True

ADVISOR_PORTAL_DUO_AUTH_ENABLED = False
ADVISOR_PORTAL_DUO_SECRET = None
ADVISOR_PORTAL_DUO_INTEGRATION_KEY = None
ADVISOR_PORTAL_DUO_API_HOST = None
ADVISOR_PORTAL_HOST = get_env_variable('ADVISOR_PORTAL_HOST', fallback_enabled=True)
ADVISOR_PORTAL_LOAN_PROFILE_MODIFYING_LIMITATION_ENABLED = False
