# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 00:11
from __future__ import unicode_literals

import accounts.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'avatars')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ('email', 'last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEmailValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('code', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('short_biography', models.TextField(blank=True)),
                ('encompass_id', models.CharField(blank=True, max_length=64, null=True)),
                ('profile_key', models.CharField(blank=True, max_length=255)),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.AboutAdvisor')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('short_biography', models.TextField(blank=True)),
                ('encompass_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_preferences', django.contrib.postgres.fields.jsonb.JSONField(default={b'email_ok': True, b'phone_ok': True, b'text_ok': False}, validators=[accounts.validators.validate_contact_preferences])),
                ('has_opted_out_of_email', models.NullBooleanField(default=False)),
                ('phone_kind', models.CharField(blank=True, choices=[(b'office', b'Office'), (b'home', b'Home'), (b'mobile', b'Mobile')], max_length=255, null=True)),
                ('preferred_language', models.CharField(blank=True, choices=[(b'cmn', b'Mandarin'), (b'en', b'English'), (b'es', b'Spanish'), (b'yue', b'Cantonese')], default=b'en', max_length=255, null=True)),
                ('preference_communication', models.CharField(blank=True, choices=[(b'phone', b'Phone'), (b'email', b'Email')], max_length=255)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('transactional_emails_subscribed', models.BooleanField(default=True)),
                ('lifecycle_emails_subscribed', models.BooleanField(default=True)),
                ('marketing_emails_subscribed', models.BooleanField(default=True)),
                ('surveys_reminders_subscribed', models.BooleanField(default=True)),
                ('purchase_timing', models.CharField(blank=True, max_length=255)),
                ('financing_contingency_date', models.DateField(blank=True, null=True)),
                ('down_payment_value', models.IntegerField(blank=True, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=255)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('inspector', models.CharField(blank=True, max_length=255)),
                ('appraisal_company', models.CharField(blank=True, max_length=512)),
                ('title_company', models.CharField(blank=True, max_length=512)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Advisor')),
                ('email_validation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CustomerEmailValidation')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('short_biography', models.TextField(blank=True)),
                ('encompass_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='defaultadvisor',
            name='default_advisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Advisor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.Realtor'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.Customer'),
        ),
    ]
