# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170202_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='nmls_number',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'NMLS #'),
        ),
    ]
