# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 09:51
from __future__ import unicode_literals

import logging

from django.db import migrations


logger = logging.getLogger('sample.accounts.migrations')


def run_migration(apps, schema_editor):
    """
    Update email in PhoneVerification records.

    """
    logger.info('Migration 0006_update_phone_verification_email is started.')

    PhoneVerification = apps.get_model('accounts', 'PhoneVerification')
    BorrowerV1 = apps.get_model('loans', 'BorrowerV1')

    for verification_obj in PhoneVerification.objects.all():
        borrower = BorrowerV1.objects.filter(home_phone=verification_obj.phone, is_active=True).first()
        verification_obj.email = borrower.email
        verification_obj.save(update_fields=['email'])

    logger.info('Migration 0006_update_phone_verification_email is finished.')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170414_0251'),
        ('loans', '0002_employmentv1_is_current_employment'),
    ]

    operations = [
        migrations.RunPython(
            run_migration,
            migrations.RunPython.noop
        ),
    ]
