# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_phone_verification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='phoneverification',
            unique_together=set([('phone', 'email')]),
        ),
    ]
