# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 00:11
from __future__ import unicode_literals

import contacts.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortgage_profiles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[(b'rate_quote_lead', b'Rate Quote Submission'), (b'consultation_request_lead', b'Consultation Lead'), (b'about_us_request', b'About Us Lead'), (b'partner_lead', b'Partner Lead'), (b'landing', b'Landing Lead'), (b'landing_page_extended_lead', b'Landing Lead (Extended)'), (b'mobile_profile_lead', b'Mobile Profile'), (b'unlicensed_state', b'Unlicensed State')], max_length=255)),
                ('advisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_answered', models.BooleanField(default=False)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('encompass_id', models.CharField(blank=True, max_length=255)),
                ('crm_id', models.CharField(blank=True, max_length=255)),
                ('crm_type', models.CharField(blank=True, max_length=255)),
                ('uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('utm_info', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('is_answered', '-created'),
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'All contact requests',
            },
            bases=(contacts.models.EncompassMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(db_index=True, max_length=10)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='NotificationReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('encompass_user_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('mortgage_profile_kind', models.CharField(blank=True, choices=[(b'purchase', b'Purchase'), (b'refinance', b'Refinance')], max_length=255)),
                ('purchase_type', models.CharField(blank=True, choices=[(b'first time homebuyer', b'First time homebuyer'), (b'selling home moving', b'Selling home / moving'), (b'second home vacation home', b'Second home / vacation home'), (b'investment property', b'Investment property reason')], max_length=255)),
                ('mortgage_timing', models.CharField(choices=[(b'immediate', b'Immediate'), (b'next_1_3_months', b'In the next 1-3 months'), (b'just_researching', b'Just researching')], max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_time', models.CharField(choices=[(b'anytime', b'Anytime'), (b'morning', b'Morning, (8-11am)'), (b'lunchtime', b'Lunchtime (11am-1pm)'), (b'afternoon', b'Afternoon (1pm-5pm)'), (b'evening', b'Evening (5pm-8pm)')], default=b'morning', max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Consultation Lead',
                'verbose_name_plural': 'Consultation Leads',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestAboutUs',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'About Us Lead',
                'verbose_name_plural': 'About Us Leads',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestLanding',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('mortgage_profile_kind', models.CharField(blank=True, choices=[(b'purchase', b'Purchase'), (b'refinance', b'Refinance')], max_length=255)),
                ('purchase_type', models.CharField(blank=True, choices=[(b'first time homebuyer', b'First time homebuyer'), (b'selling home moving', b'Selling home / moving'), (b'second home vacation home', b'Second home / vacation home'), (b'investment property', b'Investment property reason')], max_length=255)),
                ('mortgage_timing', models.CharField(choices=[(b'immediate', b'Immediate'), (b'next_1_3_months', b'In the next 1-3 months'), (b'just_researching', b'Just researching')], max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_time', models.CharField(choices=[(b'anytime', b'Anytime'), (b'morning', b'Morning, (8-11am)'), (b'lunchtime', b'Lunchtime (11am-1pm)'), (b'afternoon', b'Afternoon (1pm-5pm)'), (b'evening', b'Evening (5pm-8pm)')], default=b'morning', max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'External Lead',
                'verbose_name_plural': 'External Leads',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestLandingExtended',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mortgage_profile_kind', models.CharField(blank=True, choices=[(b'purchase', b'Purchase'), (b'refinance', b'Refinance')], max_length=255)),
                ('property_zipcode', models.CharField(blank=True, max_length=255)),
                ('property_state', models.CharField(blank=True, max_length=255)),
                ('property_county', models.CharField(blank=True, max_length=255)),
                ('is_veteran', models.NullBooleanField()),
                ('credit_rating', models.CharField(blank=True, max_length=255)),
                ('ownership_time', models.CharField(blank=True, max_length=255)),
                ('annual_income_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_debt', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_timing', models.CharField(blank=True, max_length=255)),
                ('purchase_type', models.CharField(blank=True, max_length=255)),
                ('purchase_property_value', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_down_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('refinance_purpose', models.CharField(blank=True, max_length=255)),
                ('refinance_cashout_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('refinance_property_value', models.PositiveIntegerField(blank=True, null=True)),
                ('refinance_mortgage_balance', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Landing Lead (Extended)',
                'verbose_name_plural': 'Landing Leads (Extended)',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestMobileProfile',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('credit_rating', models.CharField(blank=True, max_length=255)),
                ('annual_income_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_housing_expense', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_nonhousing_expense', models.PositiveIntegerField(blank=True, null=True)),
                ('down_payment_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('steps_progress', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('mortgage_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage_profiles.MortgageProfile')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Mobile Profile',
                'verbose_name_plural': 'Mobile Profiles',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestMortgageProfile',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('mortgage_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage_profiles.MortgageProfile')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Rate Quote Submission',
                'verbose_name_plural': 'Rate Quote Submissions',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestPartner',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Partners Lead',
                'verbose_name_plural': 'Partners Leads',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.CreateModel(
            name='ContactRequestUnlicensedState',
            fields=[
                ('contactrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.ContactRequest')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('unlicensed_state_code', models.CharField(choices=[(b'AK', b'AK'), (b'AL', b'AL'), (b'AR', b'AR'), (b'AZ', b'AZ'), (b'CA', b'CA'), (b'CO', b'CO'), (b'CT', b'CT'), (b'DC', b'DC'), (b'DE', b'DE'), (b'FL', b'FL'), (b'GA', b'GA'), (b'HI', b'HI'), (b'IA', b'IA'), (b'ID', b'ID'), (b'IL', b'IL'), (b'IN', b'IN'), (b'KS', b'KS'), (b'KY', b'KY'), (b'LA', b'LA'), (b'MA', b'MA'), (b'MD', b'MD'), (b'ME', b'ME'), (b'MI', b'MI'), (b'MN', b'MN'), (b'MO', b'MO'), (b'MS', b'MS'), (b'MT', b'MT'), (b'NC', b'NC'), (b'ND', b'ND'), (b'NE', b'NE'), (b'NH', b'NH'), (b'NJ', b'NJ'), (b'NM', b'NM'), (b'NV', b'NV'), (b'NY', b'NY'), (b'OH', b'OH'), (b'OK', b'OK'), (b'OR', b'OR'), (b'PA', b'PA'), (b'RI', b'RI'), (b'SC', b'SC'), (b'SD', b'SD'), (b'TN', b'TN'), (b'TX', b'TX'), (b'UT', b'UT'), (b'VA', b'VA'), (b'VT', b'VT'), (b'WA', b'WA'), (b'WI', b'WI'), (b'WV', b'WV'), (b'WY', b'WY')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Unlicensed State Contact Request',
                'verbose_name_plural': 'Unlicensed State Contact Requests',
            },
            bases=('contacts.contactrequest',),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.NotificationReceiver'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
