# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceRateQuoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadSource', models.CharField(default=b'sample Organic RateQuote', max_length=100)),
                ('Lead_Source_Details', models.CharField(default=b'Site', max_length=100)),
                ('Medium', models.CharField(default=b'RateQuote', max_length=100)),
                ('OwnerId', models.CharField(default=b'005G00000076Hs8', max_length=100)),
                ('Lead_Priority', models.CharField(default=b'Priority', max_length=100)),
                ('Lead_Preferred_language', models.CharField(default=b'English', max_length=100)),
                ('Pardot_Created', models.CharField(default=b'True', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesforcesampleOneRegInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadSource', models.CharField(default=b'sample Organic sampleOne', max_length=100)),
                ('Lead_Source_Details', models.CharField(default=b'Site', max_length=100)),
                ('Medium', models.CharField(default=b'PreQual', max_length=100)),
                ('OwnerId', models.CharField(default=b'005G00000076Hs8', max_length=100)),
                ('Lead_Priority', models.CharField(default=b'Special', max_length=100)),
                ('Lead_Preferred_language', models.CharField(default=b'English', max_length=100)),
                ('Pardot_Created', models.CharField(default=b'True', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
