# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_profiles', '0002_auto_20170201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprofile',
            name='conversion_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='mortgageprofile',
            name='referral_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
