# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_profiles', '0003_auto_20170217_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortechlender',
            name='program_type',
            field=models.CharField(choices=[(b'VA', b'VA'), (b'FHA', b'FHA'), (b'Non Conforming', [b'Non Conf', b'Non Conforming']), (b'Conforming', [b'Conf', b'Conforming']), (b'Jumbo', b'Jumbo'), (b'Non-Agency', b'Non-Agency')], max_length=255),
        ),
    ]
