# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_profiles', '0005_auto_20170313_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MortechLender',
            new_name='RateQuoteLender',
        ),
        migrations.RenameModel(
            old_name='MortechRequest',
            new_name='RateQuoteRequest',
        ),
        migrations.AlterModelOptions(
            name='ratequotelender',
            options={'ordering': ('-created',), 'verbose_name': 'Rate Quote Lender', 'verbose_name_plural': 'Rate Quote Lenders'},
        ),
        migrations.AlterModelOptions(
            name='ratequoterequest',
            options={'ordering': ('-created',), 'verbose_name': 'Rate Quote Request', 'verbose_name_plural': 'All Rate Quote Requests'},
        ),
        migrations.RenameField(
            model_name='mortgageprofile',
            old_name='selected_mortech_lender',
            new_name='selected_rate_quote_lender',
        ),
    ]
