# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_profiles', '0006_auto_20170331_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratequotelender',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_quote_lenders', to='mortgage_profiles.RateQuoteRequest'),
        ),
        migrations.AlterField(
            model_name='ratequoterequest',
            name='mortgage_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_quote_requests', to='mortgage_profiles.MortgageProfile'),
        ),
    ]
