# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 22:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_profiles', '0007_auto_20170331_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgageprofile',
            name='credit_rating',
        ),
    ]
